# Name: Logan Oden
# Project configuration and library dependencies

# Inputs:
# Thermositor: 10kΩ NTC (Negative Temperature Coefficient)
# Photoresistor: Light Dependent Resistor (LDR) (GL5528)
# Camera: OV2640 module (2 Megapixels)

# Outputs:
# 3 LEDs: Standard 5mm LEDs
# Fan/Motor: 3V-6V DC Motor; 
# Wire directly through GPIO pin (less power) or through included L293D motor driver chip (more power, better for simulating wind)


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    # Used for connectivity
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    